stock-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index', as: 'root'

  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  match  '/logout',   to: 'sessions#destroy', via: :delete

  resources :users, only: [:new, :create] do
    resources :transactions, only: [:new, :create, :index]
    resources :stocks, only: [:index]
  end

  # resources :users, only: [:new, :create, :show]
end

stock-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

stock-app/app/models/stock.rb
class Stock < ActiveRecord::Base
    has_many :transactions
    has_many :users, through: :transactions
end

stock-app/app/models/transaction.rb
class Transaction < ActiveRecord::Base
    belongs_to :user
    belongs_to :stock

    accepts_nested_attributes_for :stock

    validates :quantity, numericality: { only_integer: true }

    def stock_attributes=(stock)
        client = IEX::Api::Client.new(publishable_token: 'Tpk_681efd244ebe4cef8afeb7262957c2e1',
        endpoint: 'https://sandbox.iexapis.com/v1')

        self.stock = Stock.find_or_create_by(symbol: stock[:symbol])
        self.stock.price = client.price(stock[:symbol])
        self.stock.open_price = client.quote(stock[:symbol]).previous_close
        self.stock.update(stock)
    end
end

stock-app/app/models/user.rb
class User < ActiveRecord::Base
    has_many :transactions
    has_many :stocks, through: :transactions

    has_secure_password

    def deduct_from_balance(amount)
        self.balance = self.balance - amount
        self.save
    end
end

stock-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # require 'pry'
    require 'iex-ruby-client'
    include SessionsHelper

    before_action :require_signin
    rescue_from IEX::Errors::SymbolNotFoundError, with: :no_symbol_error
    rescue_from Faraday::ConnectionFailed, with: :no_connection_error

    private

    def no_symbol_error
        flash[:notice] = "Please enter a valid stock ticker symbol."
        redirect_to user_stocks_path(current_user.id)
    end

    def no_connection_error
        flash[:notice] = "Unable to connect. Please check your internet connection and try again."
        redirect_to user_stocks_path(current_user.id)
    end

    def require_signin
        unless signed_in?
            # flash[:notice] = "You must sign in to access this section."
            redirect_to new_user_path
        end
    end
end

stock-app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :require_signin, only: [:new, :create]

    def new
        @user = User.new
        @users = User.all
        @signed_out = !signed_in?
    end
      
    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            signin(@user)
            redirect_to user_stocks_path(@user.id)
        else
            flash[:notice] = "Either the email address or password are incorrect."
            redirect_to signin_path
        end
    end

    def destroy
        session.delete :user_id if session[:user_id]
        redirect_to signin_path
    end
end

stock-app/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def new
    end

    def index
        @user = current_user
        @stocks = User.find(current_user.id).stocks.uniq ||= nil
        @stock_data = Hash.new
        client = IEX::Api::Client.new(publishable_token: 'Tpk_681efd244ebe4cef8afeb7262957c2e1',
        endpoint: 'https://sandbox.iexapis.com/v1')

        @stocks.each do |stock|
            quantity = 0
            compared_to_open = ""
            price = client.price(stock.symbol)
            open_price = client.quote(stock[:symbol]).previous_close #try previous close price from quote as next best option

            @user.transactions.where(stock_id: stock.id).each do |txn|
                quantity = quantity + txn.quantity
            end

            if price > open_price
                compared_to_open = "up-since-open"
            elsif price < open_price
                compared_to_open = "down-since-open"
            end
            @stock_data[stock.symbol] = [quantity, client.price(stock.symbol), compared_to_open, open_price]
        end

        @transaction = Transaction.new(user_id: current_user.id)
        @transaction.build_stock
    end

    def create
    end

    private

    def stock_params
        params.require(:stock).permit(:symbol)
    end
end

stock-app/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    def index
        @user = current_user
        @transactions = User.find(current_user.id).transactions ||= nil
    end

    def create
        @user = current_user
        client = IEX::Api::Client.new(publishable_token: 'Tpk_681efd244ebe4cef8afeb7262957c2e1',
        endpoint: 'https://sandbox.iexapis.com/v1')
        # binding.pry
        stock_price = client.price(params[:transaction][:stock_attributes][:symbol])
        total_price = stock_price * params[:transaction][:quantity].to_i

        if @user.balance > total_price
            @transaction = Transaction.create(transaction_params)

            if @transaction.valid?
                @transaction.purchase_price = stock_price
                @transaction.purchase_date = DateTime.now
                @transaction.save
                @user.deduct_from_balance(total_price)
                redirect_to user_stocks_path(current_user.id)
            else
                flash[:notice] = "Please enter a whole number of shares to purchase."
                redirect_to user_stocks_path(current_user.id)
            end
        else
            flash[:notice] = "Not enough money. This transaction will cost $#{(total_price - @user.balance).truncate(2)} more than you have."
            redirect_to user_stocks_path(current_user.id)
        end
    end

    private

    def transaction_params
        params.require(:transaction).permit(:user_id, :quantity, :stock_id,
        stock_attributes: [:symbol])
    end
end

stock-app/app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :require_signin, only: [:new, :create]

    def new
        @signed_out = !signed_in?
        @user = User.new
    end

    def create
        @user = User.find_by(email: params[:user][:email])
        # binding.pry
        if @user
            flash[:notice] = "An account with this email address already exists."
            redirect_to new_user_path
        else
            @user = User.create(user_params)
            @user.balance = 5000.00
            @user.save
            signin(@user)
            redirect_to user_stocks_path(@user.id)
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

stock-app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        session.clear
        @signed_out = !signed_in?
    end
end

stock-app/app/helpers/application_helper.rb
module ApplicationHelper
end

stock-app/app/helpers/sessions_helper.rb
module SessionsHelper 
    def signin(user)
        session[:user_id] = user.id
    end

    def signed_in?
        session[:user_id]
    end

    def current_user
        User.find(session[:user_id])
    end

end

stock-app/app/views/layouts/_header.html.erb
<header>
    <div class="flex-container">
        <div>
            <h2 class="logotype">StockItUp</h2>
            <% if signed_in? %> 
            <div class="header-nav">
                <svg width="8" height="8" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h8v8H0z" fill="#FFF" fill-rule="evenodd"/></svg>
                <%= link_to "Portfolio", user_stocks_path(current_user), class: 'button' %>
            </div>
            <div class="header-nav">
                <svg width="8" height="8" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h8v8H0z" fill="#FFF" fill-rule="evenodd"/></svg>
                <%= link_to "Transactions", user_transactions_path(current_user), class: 'button' %>
            </div>
        </div>
        <div class="header-logout">
            <svg width="8" height="8" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h8v8H0z" fill="#FFF" fill-rule="evenodd"/></svg>
            <%= link_to "Log Out", logout_path, method: "delete", class: 'button' %>
        </div>
    <% else %>
            <div class="header-nav">
                <svg width="8" height="8" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h8v8H0z" fill="#FFF" fill-rule="evenodd"/></svg>
                <%= link_to "Sign Up", new_user_path %>
            </div>
            <div class="header-nav">
                <svg width="8" height="8" xmlns="http://www.w3.org/2000/svg"><path d="M0 0h8v8H0z" fill="#FFF" fill-rule="evenodd"/></svg>
                <%= link_to "Sign In", signin_path %>
            </div>
    <% end %>
</header>

stock-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=DM+Sans:400,700,700i&display=swap" rel="stylesheet">
  </head>

  <body class="<%= @signed_out ? 'blue-background' : '' %>">
    <%= render 'layouts/header' %>
    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

stock-app/app/views/stocks/index.html.erb
<div class="flex-container">
    <div class="portfolio-table">
        <div class="flex-container max-1000">
            <h1>Your Portfolio</h1>
            <h3 class="balance">Balance: $<%= "%.2f" % @user.balance.truncate(2) %> USD</h3>
        </div>

        <% if @stocks.size > 0 %>
            <table>
                <tr>
                    <th class="align-left">Ticker Symbol</th>
                    <th class="align-left">Quantity</th>
                    <th class="align-right">Current Value</th>
                </tr>
                <% @stock_data.each do |symbol, stock_data| %> <!-- stock_data: [quantity, price, compared_to_open, open_price] -->
                <tr>
                    <td class=<%= stock_data[2]%>><%= symbol %> Previous close: <%= "%.2f" % stock_data[3] %></td> 
                    <td><%= pluralize(stock_data[0], 'share') %></td>
                    <td class="align-right <%= stock_data[2]%>">$<%= "%.2f" % (stock_data[1] * stock_data[0]) %> </td>
                </tr>
                <% end %>
            </table>
        <% else %>
            <p>No stocks yet</p>
        <% end %>
    </div>

    <div class="stock-form">
        <h3>Buy Stocks</h3>
        <%= form_for @transaction, :url => user_transactions_path(@user.id) do |f| %>
            <%=     f.fields_for :stock do |st| %>
            <div class="stock-form-fields">
            <%=         st.label "Ticker Symbol", class: "label" %>
            <%=         st.text_field :symbol, class: "width-60" %>
            </div>
            <% end %>
            <div class="stock-form-fields">
            <%=     f.label "Quantity", class: "label" %>
            <%=     f.text_field :quantity, class: "width-60" %>
            </div>
            <%=     f.hidden_field :user_id, { :value => @user.id } %>
            <%=     f.submit "Buy" %>
        <% end %>
    </div>
</div>

stock-app/app/views/transactions/index.html.erb
<div class="transactions-table">
    <h1>Your Transactions</h1>

    <% if @transactions.size > 0 %>
    <table>
        <tr>
            <th class="align-left">Date</th>
            <th class="align-left">Ticker Symbol</th>
            <th class="align-left">Quantity</th>
            <th class="align-right">Purchase price</th>
            <th class="align-right">Total price</th>
        </tr>
        <% @transactions.each do|txn| %>
            <tr>
                <td><%= txn.purchase_date.strftime("%b %d, %Y") %></td>
                <td><%= Stock.find(txn.stock_id).symbol %>
                <td><%= txn.quantity %> shares</td>
                <td class="align-right">$<%= "%.2f" % (txn.purchase_price) %></td>
                <td class="align-right">$<%= "%.2f" % (txn.quantity * txn.purchase_price) %></td>
            </tr>
        <% end %>
    </table>

    <% else %>
        <p>No transactions yet</p>
    <% end %>
</div>

stock-app/app/views/users/new.html.erb
<div class="grid-container">
    <div class="floating-form">
        <h2>Sign up for an account</h2>
            <%= form_for @user do |f| %>
                <%=     f.label :name %>
                <%=     f.text_field :name, class: "light-blue" %><br>
                <%=     f.label :email, class: "mt-20" %>
                <%=     f.text_field :email, class: "light-blue" %><br>
                <%=     f.label :password, class: "mt-20" %>
                <%=     f.password_field :password, class: "light-blue" %><br>
                <%=     f.label :password_confirmation, 'Confirm password', class: "mt-20" %>
                <%=     f.password_field :password_confirmation, class: "light-blue" %><br>
                <%=     f.submit 'Sign Up' %>
            <% end %>
    </div>
</div>

stock-app/app/views/users/show.html.erb
<h1>Welcome <%= @user.name %>!</h1>

stock-app/app/views/welcome/index.html.erb
<h1>Welcome to the Stock App</h1>

<%= link_to "Sign Up", new_user_path %>
<%= link_to "Sign In", signin_path %>